version: 2

defaults: &defaults
  docker:
  - image: monzoandroid/ci:0.10

jobs:
  build:
    <<: *defaults
    steps:
    - checkout

    # Setup Cast SDK and Google Play Services config files
    - run: echo "castId=$CAST_APP_ID" >> app/cast.properties
    - run: echo "$GOOGLE_PLAY_SERVICES_FILE" >> app/google-services.json

    # Setup Google Cloud sdk to use for Firebase Test Lab
    - run: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
    - run: gcloud config set project audio-cast-radio
    - run: gcloud --quiet components update
    - run: gcloud --quiet components install beta
    - run: gcloud auth activate-service-account circleci@audio-cast-radio.iam.gserviceaccount.com --key-file ${HOME}/client-secret.json

    # Run compilation, checks and tests
    - run:
        name: Compile app apk and espresso tests apk
        command: ./gradlew assembleDebug assembleDebugAndroidTest --stacktrace --no-daemon
    - run:
        name: Run unit tests and lint
        command: ./gradlew testDebug lintDebug
#    - run:
#        name: Run espresso tests
#        command: gcloud firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device-ids Nexus5 --results-dir ${CIRCLE_JOB}-${CIRCLE_BUILD_NUM}

    # Save results
    - store_artifacts:
        path: app/build/outputs/apk/
        destination: apks/
    - store_artifacts:
        path: app/build/reports/
        destination: reports/
    - store_test_results:
        path: app/build/test-results/testDebugUnitTest/
    - store_test_results:
        path: ${CIRCLE_JOB}-${CIRCLE_BUILD_NUM}

workflows:
  version: 2

  workflow:
    jobs:
    - build